### PR TITLE
New Contributions Page added

### PR DESCRIPTION
**Pull request by JoKra1**
I added a .md for a new contributions page that could list the individuals that contributed to the project as well as additional information about their affiliations and personal websites.

Includes just placeholder content for now.

I also added styling to the sass file under assets and changed the config to reflect the new page content.

I worked with inline html, I hope that was okay. I saw it was permitted in the config file and just went with it since I am more used to it.

Let me know what you think! :)

### CODE REVIEW

**Comment by simabasel** [comment]
How come markdown tables didn't work and you had to use inline HTML?
https://www.markdownguide.org/extended-syntax/#tables

On Sat, Mar 28, 2020 at 9:07 PM Joshua Krause <notifications@github.com>
wrote:

> @JoKra1
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JoKra1&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=7gdHYWmrMA8y8bYw-FVjs6yc8XiAmehc1VdGBj6YZJc&s=nhKtyhp05So9BvJuiD_B2GS630wR7e26jTwWqkif04w&e=>
> requested your review on: #7
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_simabasel_psycorona.org_pull_7&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=7gdHYWmrMA8y8bYw-FVjs6yc8XiAmehc1VdGBj6YZJc&s=-a4fPbszsFcwMQRswZKH-YQOo6FoFqBG2aC0o6K7arA&e=>
> New Contributions Page added.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_simabasel_psycorona.org_pull_7-23event-2D3175141933&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=7gdHYWmrMA8y8bYw-FVjs6yc8XiAmehc1VdGBj6YZJc&s=RTsMMhY8hCJg6mBtJu7qb1qaBs41imM3fXK6E8gQ3b8&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOBXPDWXQUHJ7UJG5TZ6VBLRJYVENANCNFSM4LVUQ56A&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=7gdHYWmrMA8y8bYw-FVjs6yc8XiAmehc1VdGBj6YZJc&s=U9X4ZngiTYz7jKOmh_wuImYfGyY8ZNK9FVu1Rs2LLAw&e=>
> .
>


-- 
*Sima Basel*
*Research Associate *
Social Science Experimental Laboratory
New York University Abu Dhabi

Office Tel (UAE): +971 2 628 5676
Mobile (UAE): +971 52 399 8961

www.nyuad.nyu.edu <http://www.nyu.edu/global-ties>

**Comment by simabasel** [comment]
This is also a useful link:
https://learn.netlify.com/en/cont/markdown/#tables

Thanks!

On Sun, Mar 29, 2020 at 4:32 PM Sima Basel <sima.basel@nyu.edu> wrote:

> How come markdown tables didn't work and you had to use inline HTML?
> https://www.markdownguide.org/extended-syntax/#tables
>
> On Sat, Mar 28, 2020 at 9:07 PM Joshua Krause <notifications@github.com>
> wrote:
>
>> @JoKra1
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JoKra1&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=7gdHYWmrMA8y8bYw-FVjs6yc8XiAmehc1VdGBj6YZJc&s=nhKtyhp05So9BvJuiD_B2GS630wR7e26jTwWqkif04w&e=>
>> requested your review on: #7
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_simabasel_psycorona.org_pull_7&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=7gdHYWmrMA8y8bYw-FVjs6yc8XiAmehc1VdGBj6YZJc&s=-a4fPbszsFcwMQRswZKH-YQOo6FoFqBG2aC0o6K7arA&e=>
>> New Contributions Page added.
>>
>> —
>> You are receiving this because your review was requested.
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_simabasel_psycorona.org_pull_7-23event-2D3175141933&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=7gdHYWmrMA8y8bYw-FVjs6yc8XiAmehc1VdGBj6YZJc&s=RTsMMhY8hCJg6mBtJu7qb1qaBs41imM3fXK6E8gQ3b8&e=>,
>> or unsubscribe
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOBXPDWXQUHJ7UJG5TZ6VBLRJYVENANCNFSM4LVUQ56A&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=7gdHYWmrMA8y8bYw-FVjs6yc8XiAmehc1VdGBj6YZJc&s=U9X4ZngiTYz7jKOmh_wuImYfGyY8ZNK9FVu1Rs2LLAw&e=>
>> .
>>
>
>
> --
> *Sima Basel*
> *Research Associate *
> Social Science Experimental Laboratory
> New York University Abu Dhabi
>
> Office Tel (UAE): +971 2 628 5676
> Mobile (UAE): +971 52 399 8961
>
> www.nyuad.nyu.edu <http://www.nyu.edu/global-ties>
>


-- 
*Sima Basel*
*Research Associate *
Social Science Experimental Laboratory
New York University Abu Dhabi

Office Tel (UAE): +971 2 628 5676
Mobile (UAE): +971 52 399 8961

www.nyuad.nyu.edu <http://www.nyu.edu/global-ties>

**Comment by simabasel** [comment]
Sorry for the multiple emails, but the reason I am sharing the markdown
syntax is that we ideally want to make the .md files easy to modify for
team members who are not familiar with HTML. Please let me know if you have
any questions, and thanks!

On Sun, Mar 29, 2020 at 4:42 PM Sima Basel <sima.basel@nyu.edu> wrote:

> This is also a useful link:
> https://learn.netlify.com/en/cont/markdown/#tables
>
> Thanks!
>
> On Sun, Mar 29, 2020 at 4:32 PM Sima Basel <sima.basel@nyu.edu> wrote:
>
>> How come markdown tables didn't work and you had to use inline HTML?
>> https://www.markdownguide.org/extended-syntax/#tables
>>
>> On Sat, Mar 28, 2020 at 9:07 PM Joshua Krause <notifications@github.com>
>> wrote:
>>
>>> @JoKra1
>>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JoKra1&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=7gdHYWmrMA8y8bYw-FVjs6yc8XiAmehc1VdGBj6YZJc&s=nhKtyhp05So9BvJuiD_B2GS630wR7e26jTwWqkif04w&e=>
>>> requested your review on: #7
>>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_simabasel_psycorona.org_pull_7&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=7gdHYWmrMA8y8bYw-FVjs6yc8XiAmehc1VdGBj6YZJc&s=-a4fPbszsFcwMQRswZKH-YQOo6FoFqBG2aC0o6K7arA&e=>
>>> New Contributions Page added.
>>>
>>> —
>>> You are receiving this because your review was requested.
>>> Reply to this email directly, view it on GitHub
>>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_simabasel_psycorona.org_pull_7-23event-2D3175141933&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=7gdHYWmrMA8y8bYw-FVjs6yc8XiAmehc1VdGBj6YZJc&s=RTsMMhY8hCJg6mBtJu7qb1qaBs41imM3fXK6E8gQ3b8&e=>,
>>> or unsubscribe
>>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOBXPDWXQUHJ7UJG5TZ6VBLRJYVENANCNFSM4LVUQ56A&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=7gdHYWmrMA8y8bYw-FVjs6yc8XiAmehc1VdGBj6YZJc&s=U9X4ZngiTYz7jKOmh_wuImYfGyY8ZNK9FVu1Rs2LLAw&e=>
>>> .
>>>
>>
>>
>> --
>> *Sima Basel*
>> *Research Associate *
>> Social Science Experimental Laboratory
>> New York University Abu Dhabi
>>
>> Office Tel (UAE): +971 2 628 5676
>> Mobile (UAE): +971 52 399 8961
>>
>> www.nyuad.nyu.edu <http://www.nyu.edu/global-ties>
>>
>
>
> --
> *Sima Basel*
> *Research Associate *
> Social Science Experimental Laboratory
> New York University Abu Dhabi
>
> Office Tel (UAE): +971 2 628 5676
> Mobile (UAE): +971 52 399 8961
>
> www.nyuad.nyu.edu <http://www.nyu.edu/global-ties>
>


-- 
*Sima Basel*
*Research Associate *
Social Science Experimental Laboratory
New York University Abu Dhabi

Office Tel (UAE): +971 2 628 5676
Mobile (UAE): +971 52 399 8961

www.nyuad.nyu.edu <http://www.nyu.edu/global-ties>

**Comment by JoKra1** [comment]
Hey @simabasel ,

I noticed that the page content is placed within a div html element. There is a "problem" with 100% width tables nested in div elements: they tend to  [overflow the width of the div element](https://stackoverflow.com/questions/6601148/100-width-table-overflowing-div-container). This is not really visible on a regular display but is noticeable on phone screens. Since I liked the 100% width layout I wanted to style the table to make it work. However, I saw in the [.sass](https://github.com/simabasel/psycorona.org/blob/master/assets/bulma/sass/base/minireset.sass) that there were already some styling options assigned to the general table tag. Thus, I was unsure whether I could just re-style the general table tag effectively applying the changes to all tables.

To prevent this I decided to use a custom html class for the style changes. Since this is not possible (at least to my knowledge) using standard markdown features I went with inline html.

I fully understand your remark about ease of use though and can just change the table to regular markdown! Let me know whether you would prefer that. :) However, with the current style definitions for tables the result doesn't look great so it would be great if I could make some changes to the styling of the general table tag! Let me know whether that is an option!

Hope that clarifies my reasoning. I am sorry for the complications! In the future I will rely on pure markdown for this project.

**Comment by simabasel** [comment]
Yes, you can modify the general table style. AFAIK, we don't use tables anywhere so it should not be a problem. It is best if we keep the .md simple so even non-programmers could potentially just have access to the GitHub repository and edit the files in the future.

**Comment by JoKra1** [comment]
@simabasel 

I made the changes you requested. :-)
- Styling is now applied to the general table tag
- Inline HTML was replaced by markdown to maintain ease of use

**Pull request merged**
